# Generated by Django 4.2.30 on 2026-07-23 15:09

import candidates.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text='ఉదా: Python Developer · Fresher', max_length=150)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True, max_length=1000, verbose_name='About / Bio')),
                ('skills', models.CharField(blank=True, max_length=400)),
                ('qualification', models.CharField(blank=True, help_text='అత్యున్నత విద్యార్హత, ఉదా: B.Tech CSE', max_length=150)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher'), ('0_2', '0-2 Years'), ('2_5', '2-5 Years'), ('5_10', '5-10 Years'), ('10_plus', '10+ Years')], default='fresher', max_length=10)),
                ('current_ctc_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Current CTC (LPA)')),
                ('expected_ctc_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Expected CTC (LPA)')),
                ('hire_status', models.CharField(choices=[('available', '🟢 For Hire'), ('hired', '🔴 Hired'), ('not_looking', '⏸️ Not Looking')], default='available', max_length=15)),
                ('resume', models.FileField(blank=True, null=True, upload_to='candidate_resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'], message='రెజ్యూమ్ కేవలం PDF, DOC లేదా DOCX ఫార్మాట్ లో మాత్రమే అప్\u200cలోడ్ చేయాలి.')])),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/%Y/%m/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ssc', 'SSC / 10th'), ('intermediate', 'Intermediate / 12th'), ('graduation', 'Graduation'), ('post_graduation', 'Post Graduation'), ('other', 'Other')], max_length=20)),
                ('degree_title', models.CharField(help_text='ఉదా: B.Tech Computer Science', max_length=150, verbose_name='Degree / Course Title')),
                ('institution', models.CharField(max_length=200)),
                ('year_of_passing', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(candidates.models.current_year)])),
                ('score', models.CharField(blank=True, help_text='ఉదా: 7.8 CGPA లేదా 89%', max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-year_of_passing'],
            },
        ),
    ]
