"""
candidates/pdf_documents.py

నాలుగు క్యాండిడేట్-ఫేసింగ్ డాక్యుమెంట్‌లు -- ఇంతకుముందు ఇవన్నీ
document_resume.html / document_offer_letter.html /
document_appointment_letter.html / document_employment_letter.html లో
బ్రౌజర్ ప్రింట్ డైలాగ్ (window.print()) మీద ఆధారపడేవి. ఇప్పుడు ఇక్కడి
generate_*_pdf() ఫంక్షన్లు ReportLab తో నిజమైన PDF ఫైల్‌లు సర్వర్
లోనే జనరేట్ చేస్తాయి -- ఆయా HTML టెంప్లేట్‌లలో ఉన్న అదే డేటా,
అదే వాక్యాలు, అదే వరుసలో.
"""
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, Spacer, Table, TableStyle

from bharathub.pdf_utils import BORDER, LIGHT_BG, NAVY, build_pdf_response, get_styles


# ----------------------------------------------------------------------
# facts_table(): "Candidate Name / Company / Designation / ..." లాంటి
# label-value వరుసల బాక్స్ (al-facts CSS క్లాస్ కి సమానం) -- మూడు
# లెటర్ డాక్యుమెంట్లూ దీన్నే వాడతాయి.
# ----------------------------------------------------------------------
def _facts_table(rows, styles):
    data = [
        [Paragraph(label, styles["cell_label"]), Paragraph(str(value), styles["cell_value"])]
        for label, value in rows if value not in (None, "")
    ]
    table = Table(data, colWidths=[55 * mm, 105 * mm])
    style = [
        ("BOX", (0, 0), (-1, -1), 1, BORDER),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]
    for i in range(len(data)):
        if i % 2 == 1:
            style.append(("BACKGROUND", (0, i), (-1, i), LIGHT_BG))
    table.setStyle(TableStyle(style))
    return table


def _letter_header(title, subtitle, issued_line, styles):
    story = [
        Paragraph(title, styles["doc_title"]),
        Paragraph(subtitle, styles["doc_subtitle"]),
    ]
    if issued_line:
        story.append(Paragraph(issued_line, styles["meta_right"]))
        story.append(Spacer(1, 4))
    return story


def _footer_note(text, reference, styles):
    return [
        Spacer(1, 16),
        Paragraph(text, styles["footer"]),
    ] if not reference else [
        Spacer(1, 16),
        Paragraph(
            f"This document was generated by BharatHub based on platform records "
            f"&middot; Reference: {reference}",
            styles["footer"],
        ),
    ]


# ════════════════════════════════════════════════════════════════════
# RESUME
# ════════════════════════════════════════════════════════════════════
def generate_resume_pdf(candidate_profile, education_entries, full_name):
    styles = get_styles()
    story = []

    story.append(Paragraph(full_name, styles["name_title"]))
    if candidate_profile.headline:
        story.append(Paragraph(candidate_profile.headline, styles["headline"]))

    contact_bits = [f"✉ {candidate_profile.user.email}"]
    if candidate_profile.location:
        contact_bits.append(f"📍 {candidate_profile.location}")
    if candidate_profile.linkedin_url:
        contact_bits.append(f"🔗 {candidate_profile.linkedin_url}")
    if candidate_profile.portfolio_url:
        contact_bits.append(f"🌐 {candidate_profile.portfolio_url}")
    story.append(Paragraph("  &nbsp;&nbsp;·&nbsp;&nbsp;  ".join(contact_bits), styles["contact_line"]))
    story.append(Spacer(1, 6))

    if candidate_profile.about:
        story.append(Paragraph("ABOUT", styles["section_label"]))
        story.append(Paragraph(candidate_profile.about.replace("\n", "<br/>"), styles["body"]))

    story.append(Paragraph("KEY DETAILS", styles["section_label"]))
    fact_rows = [("Experience", candidate_profile.get_experience_level_display())]
    if candidate_profile.qualification:
        fact_rows.append(("Highest Qualification", candidate_profile.qualification))
    if candidate_profile.current_ctc_lpa:
        fact_rows.append(("Current CTC", f"Rs. {candidate_profile.current_ctc_lpa} LPA"))
    if candidate_profile.expected_ctc_lpa:
        fact_rows.append(("Expected CTC", f"Rs. {candidate_profile.expected_ctc_lpa} LPA"))
    story.append(_facts_table(fact_rows, styles))

    if candidate_profile.skills_list:
        story.append(Paragraph("SKILLS", styles["section_label"]))
        skills_html = "  ".join(f"<b>&#8226; {s}</b>" for s in candidate_profile.skills_list)
        story.append(Paragraph(skills_html, styles["body"]))

    if education_entries:
        story.append(Paragraph("EDUCATION", styles["section_label"]))
        for edu in education_entries:
            title = f"{edu.degree_title} — {edu.get_level_display()}"
            sub_bits = [edu.institution]
            if edu.year_of_passing:
                sub_bits.append(str(edu.year_of_passing))
            if edu.score:
                sub_bits.append(edu.score)
            story.append(Paragraph(f"<b>{title}</b>", styles["cell_value"]))
            story.append(Paragraph(" &middot; ".join(sub_bits), styles["party_line"]))
            story.append(Spacer(1, 6))

    bharathub_id = getattr(
        getattr(candidate_profile.user, "employee_profile", None), "bharathub_id", "",
    )
    story += _footer_note(
        f"This resume was generated from the candidate's BharatHub profile "
        f"&middot; BharatHub ID: {bharathub_id}",
        None, styles,
    )

    return build_pdf_response(
        f"{full_name.replace(' ', '_')}_Resume_BharatHub.pdf", story,
        brand_subtitle="Resume",
    )


# ════════════════════════════════════════════════════════════════════
# OFFER LETTER
# ════════════════════════════════════════════════════════════════════
def generate_offer_letter_pdf(employment, full_name):
    styles = get_styles()
    story = _letter_header(
        "Offer Letter", "Issued via BharatHub",
        f"Issued {employment.created_at:%B %d, %Y}", styles,
    )

    story.append(Paragraph(f"Dear {full_name},", styles["body"]))
    story.append(Paragraph(
        f"We are pleased to inform you that <b>{employment.employer.company_name}</b> has offered "
        f"you the position below through BharatHub. Please review the details and accept this offer.",
        styles["body"],
    ))

    bharathub_id = getattr(
        getattr(employment.candidate.user, "employee_profile", None), "bharathub_id", "",
    )
    rows = [
        ("Candidate Name", full_name),
        ("BharatHub ID", bharathub_id),
        ("Company", employment.employer.company_name),
        ("Designation", employment.designation),
    ]
    if employment.job and employment.job.department:
        rows.append(("Department", employment.job.get_department_display()))
    rows += [
        ("Date of Joining", employment.joining_date.strftime("%B %d, %Y") if employment.joining_date else ""),
        ("Salary", f"Rs. {employment.salary_lpa} LPA" if employment.salary_lpa else ""),
    ]
    story.append(_facts_table(rows, styles))

    if employment.offer_status == "accepted":
        story.append(Spacer(1, 14))
        accepted_on = employment.offer_accepted_at.strftime("%B %d, %Y") if employment.offer_accepted_at else ""
        chip = Table([[f"✅ Offer Accepted on {accepted_on}"]], colWidths=[170 * mm])
        chip.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
            ("TEXTCOLOR", (0, 0), (-1, -1), NAVY),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(chip)
    else:
        story.append(Spacer(1, 10))
        story.append(Paragraph(
            "This offer is pending your acceptance -- please accept it from your "
            "BharatHub Downloads page to confirm your joining.",
            styles["note"],
        ))

    story += _footer_note(None, f"OFR-{employment.pk}", styles)

    return build_pdf_response(
        f"Offer_Letter_{full_name.replace(' ', '_')}.pdf", story,
        brand_subtitle="Offer Letter",
    )


# ════════════════════════════════════════════════════════════════════
# APPOINTMENT (HIRE-REQUEST) CONFIRMATION LETTER
# ════════════════════════════════════════════════════════════════════
def generate_appointment_letter_pdf(hire_request, full_name):
    styles = get_styles()
    story = _letter_header(
        "Appointment Confirmation Letter", "Issued via BharatHub", None, styles,
    )

    story.append(Paragraph(f"Dear {full_name},", styles["body"]))
    story.append(Paragraph(
        f"This letter confirms that <b>{hire_request.employer.company_name}</b> sent you a hiring "
        f"invitation through BharatHub for the position below, and that you accepted it on "
        f"{hire_request.updated_at:%B %d, %Y}.",
        styles["body"],
    ))

    bharathub_id = getattr(
        getattr(hire_request.candidate.user, "employee_profile", None), "bharathub_id", "",
    )
    rows = [
        ("Candidate Name", full_name),
        ("BharatHub ID", bharathub_id),
        ("Company", hire_request.employer.company_name),
        ("Position", hire_request.job.title),
    ]
    if hire_request.job.department:
        rows.append(("Department", hire_request.job.get_department_display()))
    rows.append(("Location", hire_request.job.location))
    rows.append(("Employment Type", hire_request.job.get_job_type_display()))
    if hire_request.job.salary_min and hire_request.job.salary_max:
        rows.append(("Offered Salary Range", f"Rs. {hire_request.job.salary_min}-{hire_request.job.salary_max} LPA"))
    rows.append(("Accepted On", hire_request.updated_at.strftime("%B %d, %Y")))
    story.append(_facts_table(rows, styles))

    story.append(Spacer(1, 12))
    story.append(Paragraph(
        f"Please coordinate with {hire_request.employer.company_name} directly for your exact "
        f"joining date, designation, and compensation details.",
        styles["body"],
    ))

    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "This is a BharatHub-generated confirmation of an accepted hiring invitation, not a formal "
        "HR appointment letter. Joining date, final designation, and CTC are set directly by the "
        "employer and are not tracked on BharatHub.",
        styles["note"],
    ))

    story += _footer_note(None, f"HR-{hire_request.pk}", styles)

    return build_pdf_response(
        f"Appointment_Letter_{full_name.replace(' ', '_')}.pdf", story,
        brand_subtitle="Appointment Confirmation Letter",
    )


# ════════════════════════════════════════════════════════════════════
# EMPLOYMENT LETTER (Joining / Relieving / Experience)
# ════════════════════════════════════════════════════════════════════
def generate_employment_letter_pdf(employment, letter_type, full_name):
    styles = get_styles()

    if letter_type == "joining":
        title, subtitle = "Joining Letter", "Confirmation of employment start date"
        body_text = (
            f"This letter confirms that you joined <b>{employment.employer.company_name}</b> as "
            f"<b>{employment.designation}</b> on {employment.joining_date:%B %d, %Y}, through a hiring "
            f"process conducted via BharatHub."
        )
    elif letter_type == "relieving":
        title, subtitle = "Relieving Letter", "Confirmation of employment end date"
        body_text = (
            f"This letter confirms that you have been relieved from your role as "
            f"<b>{employment.designation}</b> at <b>{employment.employer.company_name}</b>, effective "
            f"{employment.relieving_date:%B %d, %Y}, following your resignation request which was "
            f"accepted by the employer. All dues, if any, are to be settled directly with the employer."
        )
    else:
        title, subtitle = "Experience Letter", "Confirmation of tenure and role"
        body_text = (
            f"This letter confirms that you were employed at <b>{employment.employer.company_name}</b> "
            f"as <b>{employment.designation}</b> from {employment.joining_date:%B %d, %Y} to "
            f"{employment.relieving_date:%B %d, %Y}. During this period, your conduct and performance "
            f"were found to be satisfactory."
        )

    story = _letter_header(
        title, subtitle, f"Issued {employment.relieving_date:%B %d, %Y}", styles,
    )
    story.append(Paragraph(f"Dear {full_name},", styles["body"]))
    story.append(Paragraph(body_text, styles["body"]))

    bharathub_id = getattr(
        getattr(employment.candidate.user, "employee_profile", None), "bharathub_id", "",
    )
    rows = [
        ("Candidate Name", full_name),
        ("BharatHub ID", bharathub_id),
        ("Company", employment.employer.company_name),
        ("Designation", employment.designation),
        ("Date of Joining", employment.joining_date.strftime("%B %d, %Y") if employment.joining_date else ""),
    ]
    if letter_type != "joining":
        rows.append(("Date of Relieving", employment.relieving_date.strftime("%B %d, %Y") if employment.relieving_date else ""))
    story.append(_facts_table(rows, styles))

    story.append(Spacer(1, 8))
    story.append(Paragraph(
        f"This document is generated by BharatHub based on the employment record filed by "
        f"{employment.employer.company_name} on the platform. It is not a substitute for the "
        f"employer's own official letterhead documentation where required.",
        styles["note"],
    ))

    story += _footer_note(None, f"EMP-{employment.pk}", styles)

    return build_pdf_response(
        f"{title.replace(' ', '_')}_{full_name.replace(' ', '_')}.pdf", story,
        brand_subtitle=title,
    )
