# Generated by Django 4.2.30 on 2026-07-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, choices=[('engineering', 'Engineering / Technology'), ('finance', 'Finance & Accounts'), ('marketing', 'Marketing'), ('hr', 'HR & Recruitment'), ('sales', 'Sales'), ('operations', 'Operations'), ('design', 'Design')], max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('fresher', 'Fresher (0-1 year)'), ('junior', 'Junior (1-3 years)'), ('mid', 'Mid (3-5 years)'), ('senior', 'Senior (5-8 years)'), ('lead', 'Lead (8+ years)')], max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Minimum salary in LPA', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Maximum salary in LPA', null=True)),
                ('description', models.TextField()),
                ('skills_required', models.CharField(help_text="Comma-separated, e.g. 'Python, Django, MySQL'", max_length=500)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('openings_count', models.PositiveIntegerField(default=1)),
                ('qualification', models.CharField(blank=True, choices=[('any_graduate', 'Any Graduate'), ('btech', 'B.Tech / BE'), ('mtech', 'MCA / M.Tech'), ('bca_bsc', 'BCA / B.Sc'), ('mba', 'MBA'), ('any_pg', 'Any PG')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.employerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed by candidate'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests_received', to='candidates.candidateprofile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests_sent', to='accounts.employerprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hire_requests', to='employers.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='hirerequest',
            constraint=models.UniqueConstraint(fields=('employer', 'candidate', 'job'), name='unique_hire_request_per_job'),
        ),
    ]
