# Generated by Django 4.2.30 on 2026-07-23 15:09

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('must_reset_password', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.CharField(default=accounts.models.generate_employer_id, editable=False, max_length=16, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(blank=True, choices=[('private_ltd', 'Private Limited'), ('public_ltd', 'Public Limited'), ('partnership', 'Partnership'), ('proprietorship', 'Sole Proprietorship'), ('llp', 'LLP'), ('other', 'Other')], max_length=20)),
                ('contact_person', models.CharField(blank=True, help_text='HR / ప్రధాన సంప్రదింపు వ్యక్తి పేరు', max_length=150)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField(blank=True)),
                ('other_branch_location', models.TextField(blank=True, help_text='ఇతర శాఖల ప్రదేశాలు (ఏదైనా ఉంటే, ఐచ్ఛికం)')),
                ('corporate_email', models.EmailField(max_length=254)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('cin_number', models.CharField(blank=True, max_length=21)),
                ('industry_sector', models.CharField(blank=True, max_length=100)),
                ('hq_state', models.CharField(blank=True, max_length=100)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bharathub_id', models.CharField(default=accounts.models.generate_bharathub_id, editable=False, max_length=16, unique=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('unmarried', 'Unmarried'), ('married', 'Married')], default='unmarried', max_length=20)),
                ('father_name', models.CharField(max_length=150)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/%Y/%m/')),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
