# Generated by Django 4.2.30 on 2026-07-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_note', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('new', '🆕 New'), ('review', '👁️ Under Review'), ('shortlisted', '✅ Shortlisted'), ('interview', '📅 Interview'), ('offered', '📧 Offer Sent'), ('hired', '✅ Hired'), ('rejected', '❌ Rejected')], default='new', max_length=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_datetime', models.DateTimeField(blank=True, null=True)),
                ('interview_mode', models.CharField(blank=True, choices=[('video', '🎥 Video Call'), ('phone', '📞 Phone Call'), ('in_person', '🏢 In-Person')], max_length=15)),
                ('interview_location', models.CharField(blank=True, help_text='Video call link, phone number, or office address', max_length=300)),
                ('interview_notes', models.TextField(blank=True, max_length=500)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employers.job')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('joining_date', models.DateField()),
                ('salary_lpa', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Salary (LPA)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resignation_requested', 'Resignation Requested'), ('relieved', 'Relieved')], default='active', max_length=25)),
                ('resignation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('relieving_date', models.DateField(blank=True, null=True)),
                ('offer_status', models.CharField(choices=[('pending', 'Pending Acceptance'), ('accepted', 'Accepted')], default='pending', max_length=15)),
                ('offer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='jobs.jobapplication')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'candidate'), name='unique_application_per_job'),
        ),
    ]
