# Generated by Django 4.2.30 on 2026-07-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_note', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('new', '🆕 New'), ('review', '👁️ Under Review'), ('shortlisted', '✅ Shortlisted'), ('interview', '📅 Interview'), ('offered', '📧 Offer Sent'), ('rejected', '❌ Rejected')], default='new', max_length=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employers.job')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'candidate'), name='unique_application_per_job'),
        ),
    ]
