# Generated by Django 4.2.30 on 2026-07-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_employment_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_location',
            field=models.CharField(blank=True, help_text='Video call link, phone number, or office address', max_length=300),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_mode',
            field=models.CharField(blank=True, choices=[('video', '🎥 Video Call'), ('phone', '📞 Phone Call'), ('in_person', '🏢 In-Person')], max_length=15),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
