# Generated by Django 4.2.30 on 2026-07-30 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_is_personal_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='is_personal_room',
        ),
    ]
