# Generated by Django 4.2.30 on 2026-07-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_remove_meeting_is_personal_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_personal_room',
            field=models.BooleanField(default=False),
        ),
    ]
